# Generated by Django 6.0.2 on 2026-05-10 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0010_remove_event_tag_models'),
        ('events_and_activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('kind', models.CharField(choices=[('newsletter', 'Newsletter'), ('event_report', 'Event Report')], default='newsletter', max_length=20)),
                ('issue_number', models.PositiveIntegerField(blank=True, null=True)),
                ('summary', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField()),
                ('cover_image', models.ImageField(blank=True, upload_to='news/')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_items', to='events_and_activities.event')),
                ('topics', models.ManyToManyField(blank=True, related_name='news_items', to='blog_and_news.topic')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('category', models.CharField(choices=[('article', 'Article'), ('guide', 'Technical Guide')], default='article', max_length=10)),
                ('summary', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField()),
                ('cover_image', models.ImageField(blank=True, upload_to='blog/')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='app.organizer')),
                ('topics', models.ManyToManyField(blank=True, related_name='articles', to='blog_and_news.topic')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
