# Generated by Django 6.0.2 on 2026-05-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSVPGuest',
            fields=[
            ],
            options={
                'verbose_name': 'RSVP Guest',
                'verbose_name_plural': 'RSVP Guests',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('membership.member',),
        ),
        migrations.AddField(
            model_name='member',
            name='kind',
            field=models.CharField(choices=[('member', 'Member'), ('rsvp_guest', 'RSVP Guest')], default='member', help_text='Distinguishes full community members from RSVP-only guests stored in the same table.', max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('junior', 'Junior'), ('mid', 'Mid'), ('senior', 'Senior'), ('for_fun', 'For Fun')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='primary_language',
            field=models.CharField(blank=True, choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('typescript', 'TypeScript'), ('java', 'Java'), ('csharp', 'C#'), ('cpp', 'C++'), ('c', 'C'), ('go', 'Go'), ('rust', 'Rust'), ('php', 'PHP'), ('ruby', 'Ruby'), ('swift', 'Swift'), ('kotlin', 'Kotlin'), ('dart', 'Dart'), ('r', 'R'), ('sql', 'SQL'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
