# Generated by Django 6.0.2 on 2026-02-28 10:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Counties',
            },
        ),
        migrations.CreateModel(
            name='InstitutionCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Institution categories',
            },
        ),
        migrations.CreateModel(
            name='InstitutionType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Institution types',
            },
        ),
        migrations.CreateModel(
            name='ParentMinistry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Parent ministries',
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('kuccps_number', models.PositiveIntegerField(unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='institutions', to='kenya_kuccps.county')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='institutions', to='kenya_kuccps.institutioncategory')),
                ('institution_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='institutions', to='kenya_kuccps.institutiontype')),
                ('parent_ministry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='institutions', to='kenya_kuccps.parentministry')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='kenya_kuccp_name_1fae1f_idx')],
            },
        ),
    ]
