# Generated by Django 6.0.2 on 2026-02-28 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kenya_kuccps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='institutions', to='kenya_kuccps.institutioncategory'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='institutions', to='kenya_kuccps.county'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='institution_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='institutions', to='kenya_kuccps.institutiontype'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='parent_ministry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='institutions', to='kenya_kuccps.parentministry'),
        ),
    ]
