# Generated by Django 6.0.2 on 2026-02-28 11:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kenya_kuccps', '0002_alter_institution_category_alter_institution_county_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammeGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('kuccps_id', models.CharField(help_text="Programme ID from KUCCPS (e.g. '1001').", max_length=20, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('detail_url', models.CharField(blank=True, max_length=255)),
                ('cluster_requirements', models.JSONField(blank=True, default=dict, help_text="Cluster subject requirements, e.g. {'Cluster Subject 1': 'ENG / KIS', ...}")),
                ('subject_requirements', models.JSONField(blank=True, default=dict, help_text="Minimum subject requirements, e.g. {'Subject 1': 'MAT A', ...}")),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programmes', to='kenya_kuccps.programmegroup')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProgrammeOffering',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('institution_name', models.CharField(db_index=True, max_length=255)),
                ('institution_type', models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private'), ('MOE', 'Ministry of Education'), ('OTHER_MIN', 'In Other Ministries')], max_length=20)),
                ('programme_code', models.CharField(db_index=True, help_text="Institution-specific programme code (e.g. '1700201').", max_length=20)),
                ('programme_name', models.CharField(help_text='Programme name as offered at the institution.', max_length=255)),
                ('cutoff_2023', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='KCSE 2023 Cut-off')),
                ('cutoff_2024', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='KCSE 2024 Cut-off')),
                ('cutoff_2025', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='KCSE 2025 Cut-off')),
                ('institution', models.ForeignKey(blank=True, help_text='Optional link to the Institution record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programme_offerings', to='kenya_kuccps.institution')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='kenya_kuccps.programme')),
            ],
            options={
                'ordering': ['institution_name', 'programme_name'],
                'unique_together': {('programme', 'programme_code')},
            },
        ),
    ]
