# Generated by Django 6.0.2 on 2026-02-28 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kenya_kuccps', '0003_programmegroup_programme_programmeoffering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programmeoffering',
            options={'ordering': ['institution__name', 'programme_name']},
        ),
        migrations.RemoveField(
            model_name='programmeoffering',
            name='institution_name',
        ),
        migrations.RemoveField(
            model_name='programmeoffering',
            name='institution_type',
        ),
        migrations.AlterField(
            model_name='programmeoffering',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programme_offerings', to='kenya_kuccps.institution'),
        ),
    ]
