# Generated by Django 6.0.2 on 2026-02-28 12:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kenya_kuccps', '0004_alter_programmeoffering_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DegreeCutoff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('rank', models.PositiveIntegerField(help_text='Rank within the programme category.')),
                ('category', models.CharField(db_index=True, help_text="Programme category (e.g. 'BACHELOR OF ARTS').", max_length=255)),
                ('cutoff_2018', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='2018 Cut-off')),
                ('cutoff_2019', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='2019 Cut-off')),
                ('cutoff_2020', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='2020 Cut-off')),
                ('cutoff_2021', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='2021 Cut-off')),
                ('cutoff_2022', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='2022 Cut-off')),
                ('cutoff_2023', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='2023 Cut-off')),
                ('cutoff_2024', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='2024 Cut-off')),
                ('offering', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='degree_cutoff', to='kenya_kuccps.programmeoffering')),
            ],
            options={
                'ordering': ['category', 'rank'],
            },
        ),
    ]
