# Generated by Django 6.0.2 on 2026-02-28 15:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kenya_kuccps', '0005_degreecutoff'),
    ]

    operations = [
        migrations.CreateModel(
            name='TvetSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TvetRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField(help_text='Programme number within the section.')),
                ('category', models.CharField(db_index=True, help_text="Programme category (e.g. 'Nursing', 'Engineering').", max_length=255)),
                ('subcategory', models.CharField(blank=True, help_text="Subcategory when applicable (e.g. 'Applied Biology' under Sciences).", max_length=255)),
                ('level', models.CharField(help_text="Qualification level as stated (e.g. 'Diploma', 'Diploma (Alternative A)').", max_length=255)),
                ('minimum_mean_grade', models.CharField(help_text="Minimum KCSE mean grade (e.g. 'C (plain)', 'D+').", max_length=50)),
                ('subject_requirements', models.JSONField(blank=True, default=list, help_text="Subject requirements — a list of strings, or a dict with named alternatives (e.g. {'science_based': [...], 'non_science_based': [...]}).")),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='kenya_kuccps.tvetsection')),
            ],
            options={
                'ordering': ['section', 'number', 'category', 'level'],
            },
        ),
    ]
