# Generated by Django 6.0.2 on 2026-02-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('rsvp_link', models.URLField(blank=True)),
                ('details', models.TextField()),
                ('tags', models.ManyToManyField(blank=True, related_name='events', to='app.tag')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
