# Generated by Django 6.0.2 on 2026-02-27 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initialize_member_sequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('community_role', models.CharField(help_text='Role in the Django Mombasa community', max_length=200)),
                ('professional_role', models.CharField(blank=True, help_text='Professional job title', max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('photo', models.ImageField(blank=True, upload_to='organizers/')),
                ('github_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'first_name'],
            },
        ),
    ]
