# Generated by Django 6.0.2 on 2026-02-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='member_id',
            field=models.CharField(default='', editable=False, max_length=10, unique=True),
        ),
    ]
