# Generated by Django 6.0.2 on 2026-02-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_event_slug_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='receive_email_communications',
            field=models.BooleanField(default=False, help_text='Receive email communications about events and announcements'),
        ),
        migrations.AddField(
            model_name='member',
            name='receive_regular_updates',
            field=models.BooleanField(default=False, help_text='Receive regular community updates'),
        ),
    ]
