# Generated by Django 6.0.2 on 2026-05-10 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_and_activities', '0001_initial'),
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='has_cfp',
            field=models.BooleanField(default=False, help_text='Enable the Call for Speakers section on the event detail page.'),
        ),
        migrations.AddField(
            model_name='event',
            name='has_cfv',
            field=models.BooleanField(default=False, help_text='Enable the Call for Volunteers section on the event detail page.'),
        ),
        migrations.AddField(
            model_name='event',
            name='has_rsvp',
            field=models.BooleanField(default=False, help_text='Enable the internal members-only RSVP form. When off, the external rsvp_link is used instead.'),
        ),
        migrations.CreateModel(
            name='SpeakerProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('proposed_talk_title', models.CharField(max_length=250)),
                ('talk_abstract', models.TextField()),
                ('bio', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaker_proposals', to='events_and_activities.event')),
            ],
            options={
                'db_table': 'app_speaker_proposal',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='VolunteerSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('availability', models.TextField()),
                ('skills_or_role', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_signups', to='events_and_activities.event')),
            ],
            options={
                'db_table': 'app_volunteer_signup',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='events_and_activities.event')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_rsvps', to='membership.member')),
            ],
            options={
                'db_table': 'app_rsvp',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('event', 'member'), name='unique_event_member_rsvp')],
            },
        ),
    ]
