# Generated by Django 6.0.2 on 2026-05-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_and_activities', '0002_event_has_cfp_event_has_cfv_event_has_rsvp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speakerproposal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('hold', 'On Hold')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='volunteersignup',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('hold', 'On Hold')], default='pending', max_length=10),
        ),
    ]
