# Generated by Django 6.0.2 on 2026-05-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_and_activities', '0003_alter_speakerproposal_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='When the day-before email reminder was last dispatched (set by the send_event_reminders command).', null=True),
        ),
    ]
