# Generated by Django 6.0.2 on 2026-05-28 10:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


def _backfill_check_in_tokens(apps, schema_editor):
    RSVP = apps.get_model('events_and_activities', 'RSVP')
    for rsvp in RSVP.objects.all():
        rsvp.check_in_token = uuid.uuid4()
        rsvp.save(update_fields=['check_in_token'])


class Migration(migrations.Migration):

    dependencies = [
        ('events_and_activities', '0004_event_reminder_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rsvp_capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Max number of RSVPs accepted. Leave blank for unlimited.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='rsvp_deadline',
            field=models.DateTimeField(blank=True, help_text='Latest moment members can RSVP. Leave blank for no cutoff.', null=True),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='check_in_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('hold', 'On Hold'), ('denied', 'Denied')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='check_in_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RunPython(_backfill_check_in_tokens, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='rsvp',
            name='check_in_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ScheduleSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('manual_speaker_name', models.CharField(blank=True, max_length=200)),
                ('manual_speaker_bio', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_slots', to='events_and_activities.event')),
                ('speaker_proposal', models.ForeignKey(blank=True, help_text='Pick an approved speaker proposal, or leave blank and fill the manual fields below.', limit_choices_to={'status': 'approved'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_slots', to='events_and_activities.speakerproposal')),
            ],
            options={
                'ordering': ['order', 'start_time', 'id'],
            },
        ),
    ]
