# Generated by Django 6.0.2 on 2026-05-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_and_activities', '0006_event_end_date_event_cfp_deadline_event_cfv_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='details',
            field=models.TextField(help_text='Event description shown on the public detail page. HTML is rendered as-is (links, lists, line breaks via <br>, etc.), so use real tags rather than plain newlines for formatting.'),
        ),
    ]
